version: '3.7'
services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: always
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq
    networks:
      - backend

  user-db:
    restart: always
    container_name: user-db
    image: postgres:latest
    hostname: ${USER_DB_HOST}
    ports:
      - ${USER_DB_PORT}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${USER_DB_NAME}
    networks:
      - backend

  user-app:
    build: ./user
    container_name: user-app
    image: app/user
    restart: always
    hostname: user-app
    ports:
      - 3000:3000
    volumes:
      - .env:/var/www/app/.env
    networks:
      - backend
    depends_on:
      - user-db


  wallet-db:
    restart: always
    container_name: wallet-db
    image: postgres:latest
    hostname: ${WALLET_DB_HOST}
    ports:
      - ${WALLET_DB_PORT}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${WALLET_DB_NAME}
    networks:
      - backend

  wallet-app:
    build: ./wallet
    container_name: wallet-app
    image: app/wallet
    restart: always
    hostname: wallet-app
    volumes:
      - .env:/var/www/app/.env
    networks:
      - backend
    depends_on:
      - wallet-db

networks:
  backend:
    driver: bridge

volumes:
  rabbitmq_data:
    name: rabbitmq_data
  rabbitmq_log:
    name: rabbitmq_log