version: '3.7'
services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: always
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq
    networks:
      - backend


  db:
    restart: always
    container_name: db
    image: postgres:latest
    hostname: ${POSTGRES_HOST}
    ports:
      - 5432:5432
    environment:
      - POSTGRES_MULTIPLE_DATABASES=${WALLET_DB_NAME},${USER_DB_NAME}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - backend
    volumes:
      - ./docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d

  user-app:
    build: ./user
    container_name: user-app
    image: app/user
    restart: always
    ports:
      - 3000:3000
    volumes:
      - .env:/var/www/app/.env
    networks:
      - backend
    depends_on:
      - db
    links:
      - db

  wallet-app:
    build: ./wallet
    container_name: wallet-app
    image: app/wallet
    restart: always
    volumes:
      - .env:/var/www/app/.env
    networks:
      - backend
    depends_on:
      - db
    links:
      - db

networks:
  backend:
    driver: bridge

volumes:
  rabbitmq_data:
    name: rabbitmq_data
  rabbitmq_log:
    name: rabbitmq_log