version: '3.7'
services:

  postgres:
    restart: always
    container_name: postgres
    image: postgres:latest
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    networks:
      - backend

  user:
    build: ./user
    container_name: user
    image: app/user
    restart: always
    hostname: user
    volumes:
      - .env:/var/www/app/.env
    ports:
      - ${USER_APP_PORT}:3000
    networks:
      - backend
    depends_on:
      - postgres
    links:
      - postgres

networks:
  backend:
    driver: bridge